const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false"  
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md-3";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website =process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "Made With LOVE!" 


global.devs = "" // Developer Contacts
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "24102150515";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://files.catbox.moe/anat7n.jpg" //"https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";

global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_17_02_07_16_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICA4MCxcbiAgICAgICAgMTY4LFxuICAgICAgICA2MCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDAsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTgxLFxuICAgICAgICAxMDgsXG4gICAgICAgIDY2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTEwLFxuICAgICAgICA5MyxcbiAgICAgICAgMzUsXG4gICAgICAgIDIyLFxuICAgICAgICAyMDAsXG4gICAgICAgIDU0LFxuICAgICAgICAxODEsXG4gICAgICAgIDE2MixcbiAgICAgICAgMjE3LFxuICAgICAgICAxMzksXG4gICAgICAgIDE1NCxcbiAgICAgICAgNDcsXG4gICAgICAgIDcwLFxuICAgICAgICA1NSxcbiAgICAgICAgMjAzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTcwLFxuICAgICAgICAxMDdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTE0LFxuICAgICAgICA3NCxcbiAgICAgICAgNTYsXG4gICAgICAgIDc0LFxuICAgICAgICAxMjIsXG4gICAgICAgIDcxLFxuICAgICAgICA3NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDEyLFxuICAgICAgICA5OCxcbiAgICAgICAgMTIsXG4gICAgICAgIDc3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMzEsXG4gICAgICAgIDI1MyxcbiAgICAgICAgOTMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNzEsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjA5LFxuICAgICAgICA5MCxcbiAgICAgICAgODUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTQwLFxuICAgICAgICAzMyxcbiAgICAgICAgNzAsXG4gICAgICAgIDMwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMixcbiAgICAgICAgMTY0LFxuICAgICAgICAzNixcbiAgICAgICAgMTUyLFxuICAgICAgICAzNyxcbiAgICAgICAgMTUsXG4gICAgICAgIDk1LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTgsXG4gICAgICAgIDU1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDUsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjQsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjM0LFxuICAgICAgICA0NixcbiAgICAgICAgMTE2LFxuICAgICAgICAyNixcbiAgICAgICAgMTk1LFxuICAgICAgICAxNSxcbiAgICAgICAgMjI4LFxuICAgICAgICA2NyxcbiAgICAgICAgMTkxLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTc4LFxuICAgICAgICA4NSxcbiAgICAgICAgMTgwLFxuICAgICAgICA5M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MyxcbiAgICAgICAgNjksXG4gICAgICAgIDgwLFxuICAgICAgICAxMTUsXG4gICAgICAgIDEyLFxuICAgICAgICA3NCxcbiAgICAgICAgNTcsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjMsXG4gICAgICAgIDI2LFxuICAgICAgICAyNDEsXG4gICAgICAgIDU1LFxuICAgICAgICAxODIsXG4gICAgICAgIDUyLFxuICAgICAgICAxOTMsXG4gICAgICAgIDI0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTIwLFxuICAgICAgICA0NSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyNyxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE0MSxcbiAgICAgICAgODcsXG4gICAgICAgIDYxLFxuICAgICAgICAxMTUsXG4gICAgICAgIDYsXG4gICAgICAgIDIyNixcbiAgICAgICAgNDksXG4gICAgICAgIDc1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjgsXG4gICAgICAgIDYzLFxuICAgICAgICAxOTUsXG4gICAgICAgIDg4LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTY0LFxuICAgICAgICAxMyxcbiAgICAgICAgNTIsXG4gICAgICAgIDEyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDExMixcbiAgICAgICAgMTkyLFxuICAgICAgICA4MixcbiAgICAgICAgMSxcbiAgICAgICAgODcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNzYsXG4gICAgICAgIDIxMSxcbiAgICAgICAgODAsXG4gICAgICAgIDUsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTAsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjI0LFxuICAgICAgICAxMTAsXG4gICAgICAgIDI3LFxuICAgICAgICAxODcsXG4gICAgICAgIDkyLFxuICAgICAgICAyMDQsXG4gICAgICAgIDY5LFxuICAgICAgICA4MlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0OCxcbiAgICAgICAgMjI5LFxuICAgICAgICAzLFxuICAgICAgICA4NSxcbiAgICAgICAgMTM3LFxuICAgICAgICAxODQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjI1LFxuICAgICAgICAyNTQsXG4gICAgICAgIDYzLFxuICAgICAgICAyNTMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMzksXG4gICAgICAgIDE1NixcbiAgICAgICAgMjU1LFxuICAgICAgICA3MSxcbiAgICAgICAgMjQzLFxuICAgICAgICA0NixcbiAgICAgICAgMTU0LFxuICAgICAgICAxNDksXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTMzLFxuICAgICAgICAzMCxcbiAgICAgICAgOCxcbiAgICAgICAgMjI0LFxuICAgICAgICAzMCxcbiAgICAgICAgMjExLFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNixcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgNixcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDEwNVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAzNCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA4OSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgODlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzNixcbiAgICAgICAgMTk2LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE4MCxcbiAgICAgICAgOTksXG4gICAgICAgIDYwLFxuICAgICAgICAxNjksXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTIxLFxuICAgICAgICAxODQsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjA2LFxuICAgICAgICA4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTAsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMjI1LFxuICAgICAgICAyMTYsXG4gICAgICAgIDUxLFxuICAgICAgICAyMzMsXG4gICAgICAgIDcxLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTE5LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTMxLFxuICAgICAgICAyNDQsXG4gICAgICAgIDU5LFxuICAgICAgICAxMTksXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjE5LFxuICAgICAgICAzMixcbiAgICAgICAgMTk4LFxuICAgICAgICAxOSxcbiAgICAgICAgMjIsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDIwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTU2LFxuICAgICAgICA5NixcbiAgICAgICAgMjcsXG4gICAgICAgIDUsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTIsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTIsXG4gICAgICAgIDgyLFxuICAgICAgICAzLFxuICAgICAgICAxNDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDI1LFxuICBcImFkdlNlY3JldEtleVwiOiBcImVOV0hweUttZ2w5UTdXYWIxbHRKOHZGZGluU2JYbTVEanFSaStzUW9HYjA9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiA2MSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiA2MSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcImFKeEh2eFNxVGZpSE51ZUhXQWI1ZmdcIixcbiAgXCJwaG9uZUlkXCI6IFwiYzk1MzU1ZWYtYzlmNy00MGNjLWIyMWUtMjZhYTJhOTVhYzhiXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI0OCxcbiAgICAgIDMsXG4gICAgICAyMDgsXG4gICAgICAyMTcsXG4gICAgICAxMDAsXG4gICAgICAxOTgsXG4gICAgICAxNjMsXG4gICAgICAxNTMsXG4gICAgICAxOTYsXG4gICAgICA4NyxcbiAgICAgIDUxLFxuICAgICAgOTAsXG4gICAgICAxNDEsXG4gICAgICAxOCxcbiAgICAgIDIxNSxcbiAgICAgIDExMSxcbiAgICAgIDk4LFxuICAgICAgNyxcbiAgICAgIDExMixcbiAgICAgIDE4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1NyxcbiAgICAgIDE2OCxcbiAgICAgIDQzLFxuICAgICAgMTYwLFxuICAgICAgMjM0LFxuICAgICAgNTYsXG4gICAgICAxNTgsXG4gICAgICAxNzAsXG4gICAgICAyMjgsXG4gICAgICAyMjEsXG4gICAgICAyLFxuICAgICAgMTQsXG4gICAgICA0NCxcbiAgICAgIDE3NyxcbiAgICAgIDE3MixcbiAgICAgIDE3MSxcbiAgICAgIDE5NCxcbiAgICAgIDE1NCxcbiAgICAgIDQwLFxuICAgICAgMTg5XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDT3k1b3VvREVKKzIzOE1HR0FvZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJoRmNWZllMMXNPKzBWVmdrYVZ4ZWt2L203OXYwWjQzYnVPV1AyUUF6dTIwPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIlZ3WTRPRk1Ra2N6YnJRUlpTd1NLNEk0MXRqTjNha3B3OHluc3FwRFAyMWFnTHY2OGV4a1FlMzB4S3VRSXV6SzlhRm85d1Q4a3VmdzdzV2xEelA2Nml3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInJJdlNhMVRHc1UzeUFROWIxdVArRXMrOXRzRlpJU1puZ3A2OUVpbk0rYzZ1L3QyZktHMkczZ1R0MTFQM295WDB5YytwUGQ5Rlo5bFhEaU9zRnd0VmhRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjQxMDIxNTA1MTU6NTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjIzODMxOTQ2NDEyMDUwMDo1NkBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI0MTAyMTUwNTE1OjU2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTA5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJpcGhvbmVcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTc1MjY4NTM0NyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUFERFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUMrLmpzb24iOiAie1wia2V5RGF0YVwiOlwiK2Z6N2JOS21RUTBYQWVNamVyVEpwQXdWV3FNVkJGN2NjV0JqbHhrOGhQcz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTI2NDk3MzI4MTNcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBQzEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ5M1dqSEhoczFja0xRaTQ2Wm5vaTZUdmJCQW1nNE1JK0thT1BDc2V1N2RBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMjgxNjg5NDAsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDQsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyNjQ0NjkzODgzXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUMyLmpzb24iOiAie1wia2V5RGF0YVwiOlwiOFZHdXAydWZvMzZpbXQ0QUpUOGN6RE5jM2pEVVJOaTVEN250RXhGNlhLaz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTI2NDQ3MTQ4OTFcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBQzQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJueDhCdENjRjNJSFI2cnFWN2xmaHU3dkNwejBLZHFQbGhvMWg3SDN1L1c0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMjgxNjg5NDAsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlsxLDUsMF19LFwidGltZXN0YW1wXCI6XCIxNzUyNjQ1NjM5NDA4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUM1Lmpzb24iOiAie1wia2V5RGF0YVwiOlwicEhtdm1OQ3ZvNS9SK1c2UjBQZlFpOWZZdTVDdVNUMXRFYS9VZ1JmbzllRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTI2NDU2NDA0MThcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBQzcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJHcEVHYnZWT29penlCcng3MXprUVZvWU83OWpaK1VGN0pXdkNhcVlhWFdvPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMjgxNjg5NDAsXCJjdXJyZW50SW5kZXhcIjo2LFwiZGV2aWNlSW5kZXhlc1wiOlswLDYsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyNjQ2OTUxODI5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUM5Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiUE0xVkRTUWNBaEV2dFZJYTBscDZ0TGw4bE4vd3hRWVZxZU5QajRsNUl5VT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMCw3LDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjY0NzQxNDM0OVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFDdC5qc29uIjogIntcImtleURhdGFcIjpcIjZFRmhhNmFWUEs0a2YyeWxRT1ZGZnpwRi9ZS3loaEtNd2NwSkNMcFdpQzg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAyODE2ODk0MCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyMjU5NzkyNTQ5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUN2Lmpzb24iOiAie1wia2V5RGF0YVwiOlwidEs0UU1ENTNZVnBWQTF4OGR5QU0vNFlTSFFlNFBzZVQxbjZGNFFMSXVrYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxLDJdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjYwODkxNjk5OFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFDdy5qc29uIjogIntcImtleURhdGFcIjpcInB2bmhkUGQ5UENUTWVpa2dBNG5SdG5QbXg3RVcyNU1oTlhXby8xWTlRd2M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAyODE2ODk0MCxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyNjA5MTMzNjUxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQUN5Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiQXRCVWpDVEtKcFlwMFpRNnhnWDRSMGJJVUpXYmNJa0VpYURIRFBOcDl4MD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMywwLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjY0MzA1NDY2MVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFDei5qc29uIjogIntcImtleURhdGFcIjpcIlJJV01kL0lWelB1dkFwZHhGT29FbVMzUlREUncveHJXSHBpL1ZCeFNvL2c9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAyODE2ODk0MCxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzEsNCwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTI2NDQ1NTQ2MzFcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBREEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJaZjVqQWgyNjAxSlgxT3JqOEtPTThlSFFYcG5SNEVtUE4zbmladVd6TTBJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMjgxNjg5NDAsXCJjdXJyZW50SW5kZXhcIjo4LFwiZGV2aWNlSW5kZXhlc1wiOlsxLDAsOF19LFwidGltZXN0YW1wXCI6XCIxNzUyNjc2Nzc3MjE1XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQURCLmpzb24iOiAie1wia2V5RGF0YVwiOlwiRUF0b2doeHFTUkdFVEN3VWp1ZnlRVDdGWkFxT3hJWmV2b0xjZm04RzRFND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDI4MTY4OTQwLFwiY3VycmVudEluZGV4XCI6OSxcImRldmljZUluZGV4ZXNcIjpbOSwwLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjY3Nzc1NTAzMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFERC5qc29uIjogIntcImtleURhdGFcIjpcIlR3Y3o4UWlSRU1ZT1hZZTRLN0tQK2plaUUxTWtNeittM2V3MGxxdlJYRmc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAyODE2ODk0MCxcImN1cnJlbnRJbmRleFwiOjksXCJkZXZpY2VJbmRleGVzXCI6WzksMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTI2Nzg5MTA2MjJcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBREUuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJxSlBxNXdyVTZ6OWpYUk5KSWFmanhuWDlzNmcvS1NHbXYwU0YzWGJIQnZVPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMjgxNjg5NDAsXCJjdXJyZW50SW5kZXhcIjo5LFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjY3ODkyODU4OFwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "3.0.1-developement",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "ℳℒ𝒦⛷️",
  ownername:process.env.OWNER_NAME|| "ℐ𝓈𝓇𝒶𝑒̈𝓁✰",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
